config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :blog_posts

  get 'your_posts' => 'blog_posts#your_posts'
  get 'user_posts' => 'blog_posts#user_posts'

root 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_post
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :blog_posts
         has_many :comments


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, :except => [:index]


  # Adding to User Params
  # Normally, when adding to a Resource's params, we'd visit its controller - but User has no controller,
  #  so we'll have to work in the application_controller.rb:

before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password,
   :password_confirmation, :username, :name, :location, :birthday, :avatar) }

  devise_parameter_sanitizer.permit(:account_update) { |u| u.permit({ roles: [] }, :email, :password,
  :password_confirmation, :current_password, :username, :name, :location, :birthday, :avatar) }
 end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def your_posts
    #we will use assocation (via current_user)
  end

  def user_posts
    @user = User.find(params[:id])
    # in the link to this page we'll pass the user's ID #, then use association to bring up thier blog posts
  end



  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment= Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :user_id, :location, :name, :birthday)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { rredirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :blog_post_id, :user_id, :name, :location, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(blog_post) do |f| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class:"sr-only" %>
    <%= f.text_field :title, class: "form-control", placeholder: 'Post Title' %>
  </div>

  <div class="form-group">
     <%= f.label :blog_entry, class:"sr-only" %>
    <%= f.text_area :blog_entry, class: "form-control", :rows => 20, placeholder: 'Speak Your Mind!' %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
  <h1>Blog Posts</h1>
</div>


            <% @blog_posts.each do |blog_post| %>
              <div class="col-lg-6">
                <div class="well">
                  <div class="panel-heading">
                    <h3><%= link_to blog_post.title, blog_post %></h3> </br>
                    <h5>By: <%= link_to blog_post.user.username, user_posts_path(id: blog_post.user.id) %></h5>
                    <p class="date"> <%=blog_post.created_at.strftime("%B, %d, %Y") %></p>
                  </div>
                  <div class="panel-body">
                    <p><%= blog_post.blog_entry.truncate(100) %>[<%= link_to "Read More", blog_post %>]</p>
                    <div class="panel-footer">
                      <% if user_signed_in? %>
                      <% if current_user.id == blog_post.user.id %>
                        <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-info" %>
                        <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                      <%end%>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>


		<div class="panel panel-primary">
			<div class='panel-heading'>
		 		<h3> <%= @blog_post.title %> </h3>
		 			<p class="text-right">
		 				<span class='posted-at'><%= @blog_post.created_at.strftime('%m/%d/%Y at %I:%M%p')%></span><br>
		 			</p>
			</div>
			<div class='panel-body'>
				<p>by <strong><%= link_to @blog_post.user.username, user_posts_path(id: @blog_post.user.id) %></strong></p>
				<p><%= @blog_post.blog_entry %></p>
			</div>
		</div>

		<div class="panel panel-success">
			<div class='panel-heading'>
				<h4>Make a Comment<h4>
			</div>
			<div class='panel-body'>
			<%=render 'comments/form'%>
			</div>
		</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h4>Comments</h4>
		</div>

				<% @blog_post.comments.each do |comment| %>
			<div class='panel-body'>
				<p><strong><%= link_to comment.user.username, user_posts_path(id: comment.user.id) %></strong> said: </p>
				<p><%= comment.comment_entry %></p>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }%>
			</div>
			<% end %>
	</div>

	<div>
		<% if current_user.id == @blog_post.user.id || current_user.id == comment.user_id %>
		<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
		<%= link_to 'Back', blog_posts_path %>
		<%end%>
	</div>

app/views/blog_posts/user_posts.html.erb
<div class="col-md-12">
<h1><%= image_tag(@user.avatar.url(:thumb)) %>
<%= @user.username %>'s Page
</h1>
</div>
<div class="col-md-12">
  <p><strong>Name: </strong> <%= @user.username %></p>
  <p><strong>Location: </strong> <%= @user.location %></p>
  <p><strong>Birthday: </strong> <%= @user.birthday.strftime("%m/%d/%Y") %></p>
</div>


<% @user.blog_posts.each do |blog_post| %>
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
      <%= link_to blog_post.title, blog_post%>
      </div>
      <div class="panel-body">
        <p><span class= "posted-at"><%= blog_post.created_at.strftime('%m/%d/%Y at %I:%M%p') %></span></p>
        <p><%= blog_post.blog_entry[0..150] %>... [<%= link_to "Read More", blog_post %>]</p>
      </div>
      <div class="panel-footer">
        <%= link_to 'Show', blog_post, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-info" %>
        <%= link_to 'Destroy', blog_post, method: :delete, date: { confirm: 'Are you sure?'}, class: "btn btn-danger"%>
      </div>
    </div>
  </div>
<%end%>

app/views/blog_posts/your_posts.html.erb
<% current_user.blog_posts.each do |blog_post| %>
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
      <%= link_to blog_post.title, blog_post%>
      </div>
    <div class="panel-body">
      <p><span class= "posted-at"><%= blog_post.created_at.strftime('%m/%d/%Y at %l:%M%p') %></span></p>
      <p><%= blog_post.blog_entry[0..150] %>...[<%= link_to "Read More", blog_post %>]</p>
    </div>
    <div class="panel-footer">
      <%= link_to 'Show', blog_post, class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-info" %>
      <%= link_to 'Destroy', blog_post, method: :delete, date: { confirm: 'Are you sure?'}, class: "btn btn-danger"%>
    </div>
  </div>
</div>
<%end%>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group">
    <%= f.label :comment_entry, class:"sr-only" %>
    <%= f.text_area :comment_entry, class: "form-control", placeholder: 'What do you think?', rows: 5 %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :blog_post_id, value: @blog_post.id%>
    <%= f.hidden_field :user_id, value: current_user.id%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
  <p><span class='posted-at'>posted at: <%= @blog_post.created_at.strftime('%m/%d/%Y at %I:%M%p')%></span><br></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Raleway" rel="stylesheet">

    <title>LifestyleBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if user_signed_in? %>
    <nav class="navbar navbar-default  navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a><%= link_to "Blog", blog_posts_path, class: "navbar-brand" %></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "New Blog", new_blog_post_path, class: "active" %> <span class="sr-only">(current)</span></li>
            <li><%= link_to "Your Posts", your_posts_path, class: "active" %><span class="sr-only">(current)</span></li>

          </ul>

                <div class="pull-right">
              <% if user_signed_in? %>
                <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
              <% end %>
            </div>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%else%>
    <nav class="navbar navbar-default  navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a><%= link_to "Blog", blog_posts_path, class: "navbar-brand" %></a>
        </div>
            <div class="pull-right">
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
              <%= link_to "Forgot Password", new_user_password_path, class: "btn btn-danger" %>
            </div>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    <% end %>


    <div class='container'>



    <%= yield %>
  </div>
  </body>
</html>